### PR TITLE
deployed readme to github pages

### PR DESCRIPTION
**Pull request by Satarupa22-SD**
## Pull Request description

* Made a few changes to readme file ( added contributing section)
* deployed readme to github pages

https://github.com/osl-incubator/containers-sugar/issues/11

## How to test these changes

* ```...```

## Pull Request checklists

This PR is a:
- [x] bug-fix
- [x] new feature
- [ ] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [x] this PR requires a project documentation update.

Author's checklist:
- [x] I have reviewed the changes and it contains no misspelling.
- [x] The code is well commented, especially in the parts that contain more complexity.
- [x] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Comment by xmnlab** [comment]
Hi @Satarupa22-SD , thanks for working on that!

about issue #11 it would need changes in the github actions used for release https://github.com/osl-incubator/containers-sugar/blob/main/.github/workflows/release.yaml

It would looks a bit similar to this another one: https://github.com/osl-incubator/makim/blob/main/.github/workflows/release.yaml

some key concepts here are:

- github actions https://docs.github.com/en/actions/quickstart
- semantic-release https://semantic-release.gitbook.io/semantic-release/
- Make https://makefiletutorial.com/
- mkdocs https://www.mkdocs.org/

so first, you can build the documentation locally: `mkdocs build --config-file docs/mkdocs.yaml`

and if you want to build and open that in the browser, you can run `mkdocs serve --watch docs --config-file docs/mkdocs.yaml`

so, if that works fine, you can create 2 "Make" targets one for each previous mkdocs command
for example: 

```make
build:
        mkdocs build --config-file docs/mkdocs.yaml

preview:
        mkdocs serve --watch docs --config-file docs/mkdocs.yaml
```

Note: remember that in a makefile the indentation is done with TAB not empty spaces

And the last piece would be adding that to the github actions (similar to what we are doing in the makim project)

maybe there is a bunch of new concepts here for you, so feel free to take your time to read all the references and also feel free to ping me here if you have any question :)

**Comment by xmnlab** [comment]
@Satarupa22-SD let me know if you still want to work on this PR :) thanks!

**Comment by Satarupa22-SD** [comment]
Sure Ivan, I would like to continue working on this project. Somethings
have come up very urgently hence the delay.

**Comment by xmnlab** [comment]
ok no problem .. just checking :)
thanks for the feedback :)

**Comment by xmnlab** [comment]
@Satarupa22-SD, any plans to move this PR forward?
if you don't have time, don't worry, it is totally ok.

**Comment by xmnlab** [comment]
@Satarupa22-SD I am closing this issue for now
feel free to reopen that when you want

**Pull request closed without merging**
